"""
code_generator.py — Deterministic analysis script generator for Helix.AI.

Each public function returns a self-contained Python script (as a string) that:
  • imports only from backend.*
  • embeds all parameters directly (no CLI args needed)
  • writes every output (plots as .png, tables as .json/.csv) to a run_dir/
  • prints a single JSON summary line to stdout when executed

The "Parameters" block near the top of each script is deliberately isolated so
that an LLM can locate and patch it in one focused edit without touching the
analysis logic.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any, Dict, Optional

# Project root is two levels up from this file (backend/ → Helix.AI/)
_PROJECT_ROOT = str(Path(__file__).parent.parent.resolve())


# ── helpers ──────────────────────────────────────────────────────────────────

def _escape(v: Any) -> str:
    """Return a Python-literal representation of v."""
    if isinstance(v, str):
        return repr(v)
    return repr(v)


# ── bulk RNA-seq ──────────────────────────────────────────────────────────────

_BULK_RNASEQ_TEMPLATE = '''\
#!/usr/bin/env python3
"""
Bulk RNA-seq Differential Expression Analysis
Generated by Helix.AI  |  run_id: {run_id}  |  session: {session_id}
"""
import sys, json, base64
from pathlib import Path

# ── Parameters ────────────────────────────────────────────────────────────────
# Edit this block to change the analysis and re-run the script.
COUNT_MATRIX     = {count_matrix}
SAMPLE_METADATA  = {sample_metadata}
DESIGN_FORMULA   = {design_formula}
ALPHA            = {alpha}
X_SCALE          = {x_scale}   # "log2" or "linear"
RUN_DIR          = Path({run_dir})
# ─────────────────────────────────────────────────────────────────────────────

sys.path.insert(0, {project_root})
from backend import bulk_rnaseq as _mod

RUN_DIR.mkdir(parents=True, exist_ok=True)
plots_dir  = RUN_DIR / "plots";  plots_dir.mkdir(exist_ok=True)
tables_dir = RUN_DIR / "tables"; tables_dir.mkdir(exist_ok=True)

result = _mod.run_deseq2_analysis(
    count_matrix=COUNT_MATRIX,
    sample_metadata=SAMPLE_METADATA,
    design_formula=DESIGN_FORMULA,
    alpha=ALPHA,
    x_scale=X_SCALE,
)

# ── Save plots ────────────────────────────────────────────────────────────────
plot_paths = {{}}
for key, b64 in (result.get("plots") or {{}}).items():
    if not b64:
        continue
    out = plots_dir / f"{{key}}.png"
    out.write_bytes(base64.b64decode(b64))
    plot_paths[key] = str(out)

# ── Save DE tables ────────────────────────────────────────────────────────────
table_paths = {{}}
for key, records in (result.get("de_results") or {{}}).items():
    if not records:
        continue
    out = tables_dir / f"de_{{key}}.json"
    out.write_text(json.dumps(records, indent=2))
    table_paths[key] = str(out)

# ── Summary ───────────────────────────────────────────────────────────────────
summary = {{
    "status":       result.get("status", "success"),
    "n_samples":    result.get("n_samples"),
    "n_genes_total": result.get("n_genes_total"),
    "summary":      result.get("summary"),
    "top_genes":    result.get("top_genes"),
    "plot_paths":   plot_paths,
    "table_paths":  table_paths,
    "x_scale":      X_SCALE,
    "run_dir":      str(RUN_DIR),
}}
print(json.dumps(summary))
'''


def bulk_rnaseq_script(
    *,
    run_id: str,
    session_id: str,
    run_dir: str,
    count_matrix: str,
    sample_metadata: str,
    design_formula: str = "~condition",
    alpha: float = 0.05,
    x_scale: str = "log2",
) -> str:
    return _BULK_RNASEQ_TEMPLATE.format(
        run_id=run_id,
        session_id=session_id,
        count_matrix=_escape(count_matrix),
        sample_metadata=_escape(sample_metadata),
        design_formula=_escape(design_formula),
        alpha=_escape(alpha),
        x_scale=_escape(x_scale),
        run_dir=_escape(run_dir),
        project_root=_escape(_PROJECT_ROOT),
    )


# ── single-cell RNA-seq ───────────────────────────────────────────────────────

_SCRNA_TEMPLATE = '''\
#!/usr/bin/env python3
"""
Single-Cell RNA-seq Analysis
Generated by Helix.AI  |  run_id: {run_id}  |  session: {session_id}
"""
import sys, json, base64
from pathlib import Path

# ── Parameters ────────────────────────────────────────────────────────────────
DATA_FILE   = {data_file}     # S3 URI or local path; None → synthetic
DATA_FORMAT = {data_format}   # "10x" | "csv" | "h5"
RESOLUTION  = {resolution}    # Leiden clustering resolution
STEPS       = {steps}         # "all" or comma-separated steps
N_CELLS     = {n_cells}       # cells in synthetic fallback
N_GENES     = {n_genes}       # genes in synthetic fallback
COLOR_BY    = {color_by}      # column for t-SNE colouring ("cluster" | "cell_type" | …)
RUN_DIR     = Path({run_dir})
# ─────────────────────────────────────────────────────────────────────────────

sys.path.insert(0, {project_root})
from backend import single_cell_analysis as _mod

RUN_DIR.mkdir(parents=True, exist_ok=True)
plots_dir = RUN_DIR / "plots"; plots_dir.mkdir(exist_ok=True)

result = _mod.analyze_single_cell_data(
    data_file=DATA_FILE,
    data_format=DATA_FORMAT,
    resolution=RESOLUTION,
    steps=STEPS,
    n_cells=N_CELLS,
    n_genes=N_GENES,
)

plot_paths = {{}}
for key, b64 in (result.get("plots") or {{}}).items():
    if not b64:
        continue
    out = plots_dir / f"{{key}}.png"
    out.write_bytes(base64.b64decode(b64))
    plot_paths[key] = str(out)

summary = {{
    "status":      result.get("status", "success"),
    "n_cells":     result.get("n_cells"),
    "n_genes":     result.get("n_genes"),
    "n_clusters":  result.get("n_clusters"),
    "resolution":  RESOLUTION,
    "plot_paths":  plot_paths,
    "run_dir":     str(RUN_DIR),
}}
print(json.dumps(summary))
'''


def single_cell_script(
    *,
    run_id: str,
    session_id: str,
    run_dir: str,
    data_file: Optional[str] = None,
    data_format: str = "10x",
    resolution: float = 0.5,
    steps: str = "all",
    n_cells: int = 600,
    n_genes: int = 300,
    color_by: str = "cluster",
) -> str:
    return _SCRNA_TEMPLATE.format(
        run_id=run_id,
        session_id=session_id,
        data_file=_escape(data_file),
        data_format=_escape(data_format),
        resolution=_escape(resolution),
        steps=_escape(steps),
        n_cells=_escape(n_cells),
        n_genes=_escape(n_genes),
        color_by=_escape(color_by),
        run_dir=_escape(run_dir),
        project_root=_escape(_PROJECT_ROOT),
    )


# ── phylogenetic tree ─────────────────────────────────────────────────────────

_PHYLO_TEMPLATE = '''\
#!/usr/bin/env python3
"""
Phylogenetic Tree Analysis
Generated by Helix.AI  |  run_id: {run_id}  |  session: {session_id}
"""
import sys, json, base64
from pathlib import Path

# ── Parameters ────────────────────────────────────────────────────────────────
ALIGNED_SEQUENCES = {aligned_sequences}  # FASTA string; "" → built-in SARS-CoV-2
RUN_DIR           = Path({run_dir})
# ─────────────────────────────────────────────────────────────────────────────

sys.path.insert(0, {project_root})
from backend import phylogenetic_tree as _mod

RUN_DIR.mkdir(parents=True, exist_ok=True)
plots_dir = RUN_DIR / "plots"; plots_dir.mkdir(exist_ok=True)

result = _mod.run_phylogenetic_tree_raw(ALIGNED_SEQUENCES)

plot_paths = {{}}
for key in ("tree_plot_b64", "dist_matrix_b64", "ete_visualization", "plot"):
    b64 = result.get(key)
    if not b64:
        continue
    out = plots_dir / f"{{key}}.png"
    out.write_bytes(base64.b64decode(b64))
    plot_paths[key] = str(out)

newick_path = None
if result.get("tree_newick"):
    np_ = RUN_DIR / "tree.nwk"
    np_.write_text(result["tree_newick"])
    newick_path = str(np_)

summary = {{
    "status":      result.get("status", "success"),
    "statistics":  result.get("statistics"),
    "plot_paths":  plot_paths,
    "newick_path": newick_path,
    "run_dir":     str(RUN_DIR),
}}
print(json.dumps(summary))
'''


def phylogenetic_tree_script(
    *,
    run_id: str,
    session_id: str,
    run_dir: str,
    aligned_sequences: str = "",
) -> str:
    return _PHYLO_TEMPLATE.format(
        run_id=run_id,
        session_id=session_id,
        aligned_sequences=_escape(aligned_sequences),
        run_dir=_escape(run_dir),
        project_root=_escape(_PROJECT_ROOT),
    )


# ── FastQC / Amplicon QC ──────────────────────────────────────────────────────

_FASTQC_TEMPLATE = '''\
#!/usr/bin/env python3
"""
FastQC / Amplicon Quality Assessment
Generated by Helix.AI  |  run_id: {run_id}  |  session: {session_id}
"""
import sys, json
from pathlib import Path

# ── Parameters ────────────────────────────────────────────────────────────────
INPUT_R1  = {input_r1}   # S3 URI or local path to R1 FASTQ(.gz)
INPUT_R2  = {input_r2}   # S3 URI or local path to R2 FASTQ(.gz); None → skip
MIN_QUAL  = {min_qual}   # Minimum average base quality for passing
RUN_DIR   = Path({run_dir})
# ─────────────────────────────────────────────────────────────────────────────

sys.path.insert(0, {project_root})
from backend.agent_tools import fastqc_quality_analysis as _tool

RUN_DIR.mkdir(parents=True, exist_ok=True)

result = _tool(
    input_r1=INPUT_R1,
    input_r2=INPUT_R2,
    min_qual=MIN_QUAL,
    _from_broker=True,
)

summary_path = RUN_DIR / "qc_summary.json"
summary_path.write_text(json.dumps(result, indent=2))

summary = {{
    "status":        result.get("status", "completed"),
    "mode":          result.get("mode"),
    "pct_passing_r1": result.get("pct_passing_r1"),
    "pct_passing_r2": result.get("pct_passing_r2"),
    "summary_path":  str(summary_path),
    "run_dir":       str(RUN_DIR),
}}
print(json.dumps(summary))
'''


def fastqc_script(
    *,
    run_id: str,
    session_id: str,
    run_dir: str,
    input_r1: str = "",
    input_r2: Optional[str] = None,
    min_qual: int = 20,
) -> str:
    return _FASTQC_TEMPLATE.format(
        run_id=run_id,
        session_id=session_id,
        input_r1=_escape(input_r1),
        input_r2=_escape(input_r2),
        min_qual=_escape(min_qual),
        run_dir=_escape(run_dir),
        project_root=_escape(_PROJECT_ROOT),
    )


# ── dispatcher ────────────────────────────────────────────────────────────────

_GENERATORS: Dict[str, Any] = {
    "bulk_rnaseq_analysis": bulk_rnaseq_script,
    "single_cell_analysis": single_cell_script,
    "phylogenetic_tree":    phylogenetic_tree_script,
    "fastqc_quality_analysis": fastqc_script,
}


def generate(
    tool_name: str,
    params: Dict[str, Any],
    *,
    run_id: str,
    session_id: str,
    run_dir: str,
) -> Optional[str]:
    """Return the analysis script for *tool_name*, or None if unsupported."""
    fn = _GENERATORS.get(tool_name)
    if fn is None:
        return None
    safe_params = {k: v for k, v in params.items() if k not in ("needs_inputs",)}
    try:
        return fn(run_id=run_id, session_id=session_id, run_dir=run_dir, **safe_params)
    except TypeError:
        # Unknown extra params — strip to only what the generator accepts
        import inspect
        sig = inspect.signature(fn)
        known = {k for k in sig.parameters if k not in ("run_id", "session_id", "run_dir")}
        filtered = {k: v for k, v in safe_params.items() if k in known}
        return fn(run_id=run_id, session_id=session_id, run_dir=run_dir, **filtered)
