#!/usr/bin/env bash
set -euo pipefail

# Setup script to help configure AWS deployment
# This script helps users set up their deployment configuration

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/deploy.config"

print_info() {
    echo -e "\033[0;34m[INFO]\033[0m $1"
}

print_success() {
    echo -e "\033[0;32m[SUCCESS]\033[0m $1"
}

print_warning() {
    echo -e "\033[1;33m[WARNING]\033[0m $1"
}

print_error() {
    echo -e "\033[0;31m[ERROR]\033[0m $1"
}

print_info "Helix.AI AWS Deployment Setup"
print_info "=============================="

# Check if config already exists
if [ -f "${CONFIG_FILE}" ]; then
    print_warning "Configuration file already exists: ${CONFIG_FILE}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_info "Keeping existing configuration"
        exit 0
    fi
fi

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    print_error "AWS CLI is not installed. Please install it first."
    exit 1
fi

# Get AWS account ID
print_info "Getting AWS account information..."
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "")
if [ -z "${AWS_ACCOUNT_ID}" ]; then
    print_error "Could not determine AWS account ID. Please run 'aws configure' first."
    exit 1
fi

# Get AWS region
AWS_REGION=$(aws configure get region 2>/dev/null || echo "us-east-1")
print_info "Detected AWS Account ID: ${AWS_ACCOUNT_ID}"
print_info "Detected AWS Region: ${AWS_REGION}"

# Prompt for configuration
print_info ""
print_info "Please provide the following information:"
print_info ""

read -p "AWS Region [${AWS_REGION}]: " INPUT_REGION
AWS_REGION="${INPUT_REGION:-${AWS_REGION}}"

read -p "ECR Repository Name [helix-backend]: " ECR_REPO
ECR_REPO="${ECR_REPO:-helix-backend}"

read -p "S3 Bucket Name [helix-frontend-bucket-${AWS_ACCOUNT_ID}-${AWS_REGION}]: " S3_BUCKET
S3_BUCKET="${S3_BUCKET:-helix-frontend-bucket-${AWS_ACCOUNT_ID}-${AWS_REGION}}"

read -p "CloudFront Distribution ID (optional, press Enter to skip): " CF_DIST_ID

read -p "ECS Cluster Name (optional, press Enter to skip): " ECS_CLUSTER
read -p "ECS Service Name (optional, press Enter to skip): " ECS_SERVICE
read -p "ECS Task Definition Family (optional, press Enter to skip): " ECS_TASK_FAMILY

echo ""
print_info "Backend API URL:"
echo "  This should be your ALB DNS name. You can:"
echo "  1. Get it automatically (recommended): ./get-alb-url.sh"
echo "  2. Find it in CloudFormation stack outputs"
echo "  3. Enter it manually"
echo ""
read -p "Backend API URL [press Enter to fetch from stack or type URL]: " API_URL
if [ -z "${API_URL}" ]; then
    print_info "Fetching ALB URL from CloudFormation stack..."
    if [ -f "${SCRIPT_DIR}/get-alb-url.sh" ]; then
        ALB_OUTPUT=$("${SCRIPT_DIR}/get-alb-url.sh" 2>&1 | grep -A1 "Backend API URL:" | tail -1 | sed 's/.*: //')
        if [ -n "${ALB_OUTPUT}" ] && [[ "${ALB_OUTPUT}" =~ ^http ]]; then
            API_URL="${ALB_OUTPUT}"
            print_success "Found ALB URL: ${API_URL}"
        else
            print_warning "Could not auto-fetch ALB URL. Please enter manually or run: ./get-alb-url.sh"
            read -p "Backend API URL: " API_URL
        fi
    else
        print_warning "Helper script not found. Please enter the URL manually."
        read -p "Backend API URL (e.g., http://your-alb-dns.region.elb.amazonaws.com): " API_URL
    fi
fi

# Create configuration file
print_info ""
print_info "Creating configuration file..."

cat > "${CONFIG_FILE}" << EOF
# Helix.AI AWS Deployment Configuration
# Generated by setup-deployment.sh on $(date)

# AWS Configuration
AWS_REGION=${AWS_REGION}
AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}

# ECR Configuration
ECR_REPOSITORY=${ECR_REPO}
IMAGE_TAG=latest

# S3 Configuration
S3_BUCKET=${S3_BUCKET}

# CloudFront Configuration (optional)
CLOUDFRONT_DISTRIBUTION_ID=${CF_DIST_ID:-}

# ECS Configuration (optional - for automatic service updates)
ECS_CLUSTER_NAME=${ECS_CLUSTER:-}
ECS_SERVICE_NAME=${ECS_SERVICE:-}
ECS_TASK_DEFINITION_FAMILY=${ECS_TASK_FAMILY:-}

# Frontend Configuration
VITE_API_BASE_URL=${API_URL:-}

# Deployment Options
SKIP_BACKEND=false
SKIP_FRONTEND=false
SKIP_CLOUDFRONT_INVALIDATION=false
SKIP_ECS_UPDATE=false
EOF

print_success "Configuration file created: ${CONFIG_FILE}"
print_info ""
print_info "Next steps:"
print_info "1. Review and edit ${CONFIG_FILE} if needed"
print_info "2. Deploy infrastructure: cd infrastructure && cdk deploy"
print_info "3. Deploy application: ./scripts/aws/deploy.sh"
print_info ""

